import {
  isArrayType,
  isBoolType,
  isCharType,
  isDoubleType,
  isFastMapType,
  isFastSetType,
  isFloatType,
  isI16Type,
  isI32Type,
  isI64Type,
  isI8Type,
  isMapType,
  isOptionalType,
  isPlainIntEnumType,
  isRefType,
  isSetType,
  isStringType,
  isTupleType,
  isU16Type,
  isU32Type,
  isU64Type,
  isU8Type,
} from '../IDL';
import type {
  EmitItem,
  Emitter,
  Enum,
  FileGenerator,
  NEnum,
  ObjType,
  OptType,
  SEnum,
  SubType,
  Types,
} from '../types';
import { MakeGenerator } from './api';

async function header(writer: Bun.FileSink): Promise<void> {
  await writer.write(`// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from www/Shared/Definitions.ts by running 'bun gen'
// If you need to change this file, edit www/Shared/Definitions.ts and run
// 'bun gen' again. Or, if you need to change the generation process, edit
// scripts/emitters/cpp.ts and run 'bun gen' again.
// DO NOT EDIT THIS FILE DIRECTLY!!!

#pragma once

#ifndef SHARED_CONSTANTS_HPP
#define SHARED_CONSTANTS_HPP

#include <cstdint>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <string_view>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include <crow/json.h>

#include "json_pickling.hpp"

namespace Shared {
template <typename T>
constexpr std::optional<T> from_string(const std::string_view& str);
`);
}

const outsideNamespace: string[] = [];

function addNonShared(lines: string): void {
  outsideNamespace.push(lines);
}

async function footer(writer: Bun.FileSink): Promise<void> {
  await writer.write(`

} // namespace Shared 
${outsideNamespace.join('\n')}

#endif // SHARED_CONSTANTS_HPP
`);
}

function getTypeName(type: Types, scoped?: boolean): string {
  if (isU8Type(type)) {
    return 'std::uint8_t';
  } else if (isI8Type(type)) {
    return 'std::int8_t';
  } else if (isU16Type(type)) {
    return 'std::uint16_t';
  } else if (isI16Type(type)) {
    return 'std::int16_t';
  } else if (isU32Type(type)) {
    return 'std::uint32_t';
  } else if (isI32Type(type)) {
    return 'std::int32_t';
  } else if (isU64Type(type)) {
    return 'std::uint64_t';
  } else if (isI64Type(type)) {
    return 'std::int64_t';
  } else if (isStringType(type)) {
    return 'std::string';
  } else if (isCharType(type)) {
    return 'char';
  } else if (isBoolType(type)) {
    return 'bool';
  } else if (isFloatType(type)) {
    return 'float';
  } else if (isDoubleType(type)) {
    return 'double';
  } else if (isRefType(type)) {
    return scoped ? 'Shared::' + type.r : type.r; // Reference type, just return the name
  } else if (isArrayType(type)) {
    return `std::vector<${getTypeName(type.d, !!scoped)}>`;
  } else if (isSetType(type)) {
    return `std::set<${getTypeName(type.d, !!scoped)}>`;
  } else if (isFastSetType(type)) {
    return `std::unordered_set<${getTypeName(type.d, !!scoped)}>`;
  } else if (isMapType(type)) {
    return `std::map<${getTypeName(type.k, !!scoped)}, ${getTypeName(type.v, !!scoped)}>`;
  } else if (isFastMapType(type)) {
    return `std::unordered_map<${getTypeName(type.k, !!scoped)}, ${getTypeName(type.v, !!scoped)}>`;
  } else if (isTupleType(type)) {
    return `std::tuple<${type.l.map((a) => getTypeName(a, !!scoped)).join(', ')}>`;
  } else if (isOptionalType(type)) {
    return `std::optional<${getTypeName(type.d, !!scoped)}>`;
  }
  throw new Error(`Unsupported unnamed type: ${JSON.stringify(type)}`);
}

const enumType: EmitItem<Enum> = async (writer, name, item) => {
  const typeName = isPlainIntEnumType(item.u)
    ? ''
    : ` : ${getTypeName(item.u)}`;
  await writer.write(`
#pragma region numeric enum ${name}
enum class ${name}${typeName} {
  ${item.v.join(',\n  ')}
};

inline constexpr bool is_valid(${name} _value) {
  switch (_value) {
${item.v.map((val) => `    case ${name}::${val}:`).join('\n')}
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(${name} _value) {
  switch (_value) {
${item.v
  .map(
    (val) => `    case ${name}::${val}:
      return "${val}";`,
  )
  .join('\n')}
    default:
      return "<unknown>";
  }
}
#pragma endregion numeric enum ${name}

`);
};

const numEnumType: EmitItem<NEnum> = async (writer, name, item) => {
  const typeName = isPlainIntEnumType(item.u)
    ? ''
    : ` : ${getTypeName(item.u)}`;
  await writer.write(`
#pragma region linear enum ${name}
enum class ${name}${typeName} {
${Object.entries(item.v)
  .map(([key, value]) => `  ${key} = ${value},`)
  .join('\n')}
};

inline constexpr bool is_valid(${name} _value) {
  switch (_value) {
${Object.entries(item.v)
  .map(([key]) => `    case ${name}::${key}:`)
  .join('\n')}
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(${name} _value) {
  switch (_value) {
${Object.entries(item.v)
  .map(
    ([key, _]) => `    case ${name}::${key}:
      return "${key}";`,
  )
  .join('\n')}
    default:
      return "<unknown>";
  }
}

#pragma endregion linear enum ${name}
`);
};

const strEnumType: EmitItem<SEnum> = async (writer, name, item) => {
  await writer.write(`
#pragma region string enum ${name}

enum class ${name} {
  ${Object.keys(item.v)
    .map((key) => `${key}`)
    .join(',\n  ')}
};

inline constexpr bool is_valid(${name} _value) {
  switch (_value) {
${Object.entries(item.v)
  .map(([key]) => `    case ${name}::${key}:`)
  .join('\n')}
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(${name} _value) {
  switch (_value) {
${Object.entries(item.v)
  .map(
    ([key, val]) => `    case ${name}::${key}:
      return "${val}";`,
  )
  .join('\n')}
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<${name}>
from_string<${name}>(const std::string_view& str) {
${Object.entries(item.v)
  .map(
    ([key, val]) => `  if (str == "${val}")
    return ${name}::${key};`,
  )
  .join('\n')}
  return std::nullopt;
}

#pragma endregion string enum ${name}
`);

  addNonShared(`#pragma region JSON serialization for string enum ${name}
template <>
inline crow::json::wvalue to_json<Shared::${name}>(
    Shared::${name} _value) {
  return to_json(to_string(_value));
} 
template <>
struct impl_from_json<Shared::${name}> {
  static inline std::optional<Shared::${name}> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::${name}>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum ${name}
`);
};
const objType: EmitItem<ObjType> = async (writer, name, item) => {
  await writer.write(`\nstruct ${name} {\n`);
  for (const [key, value] of Object.entries(item.d)) {
    const typeName = getTypeName(value);
    await writer.write(`  ${typeName} ${key};\n`);
  }
  await writer.write('};\n');
  const required = Object.entries(item.d).filter(
    ([_, v]) => !isOptionalType(v),
  );
  const optional = Object.entries(item.d).filter(([_, v]) => isOptionalType(v));
  addNonShared(`
#pragma region JSON serialization for object ${name}
template <> 
struct impl_to_json<Shared::${name}> { 
  static inline crow::json::wvalue process(
      const Shared::${name}& _value) {
    crow::json::wvalue _res;
    ${required
      .map(([key, _]) => `_res["${key}"] = to_json(_value.${key});`)
      .join('\n    ')}
    ${optional
      .map(
        ([key, _]) => `if (_value.${key}) {
       _res["${key}"] = to_json(*_value.${key});
      }`,
      )
      .join('\n    ')}
    return _res;
  }
};

template <>
inline std::optional<Shared::${name}>
from_json<Shared::${name}>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::${name} _res;
  ${required
    .map(
      ([key, value]) => `
  if (!_value.has("${key}"))
    return std::nullopt;
  auto _${key}_opt_ = from_json<${getTypeName(value, true)}>(_value["${key}"]);
  if (!_${key}_opt_.has_value())
    return std::nullopt;
  _res.${key} = std::move(*_${key}_opt_);`,
    )
    .join('\n  ')}
  ${optional
    .map(
      ([key, value]) => `
  if (_value.has("${key}")) {
    auto _${key}_opt_ = from_json<${getTypeName((value as OptType).d, true)}>(_value["${key}"]);
    if (!_${key}_opt_.has_value())
      return std::nullopt;
    _res.${key} = std::move(*_${key}_opt_);
  } else {
    _res.${key} = std::nullopt;
  }`,
    )
    .join('\n  ')}
  return _res;
}
#pragma endregion JSON serialization for object ${name}
`);
};

const subType: EmitItem<SubType> = async (writer, name, item) => {
  await writer.write(`\nstruct ${name} : ${item.p} {\n`);
  for (const [key, value] of Object.entries(item.d)) {
    const typeName = getTypeName(value);
    await writer.write(`  ${typeName} ${key};\n`);
  }
  await writer.write('};\n');
  addNonShared(`
#pragma region JSON serialization for object ${name}
template <> 
struct impl_to_json<Shared::${name}> { 
  static inline crow::json::wvalue process(
      const Shared::${name}& _value) {
    crow::json::wvalue _res = impl_to_json<Shared::${item.p}>::process(_value);
    ${Object.entries(item.d)
      .map(([key]) => `_res["${key}"] = to_json(_value.${key});`)
      .join('\n    ')}
    return _res;
  }
};

template <>
inline std::optional<Shared::${name}>
from_json<Shared::${name}>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  std::optional<Shared::${item.p}> _base = from_json<Shared::${item.p}>(_value);
  if (!_base.has_value())
    return std::nullopt;
  
  ${Object.entries(item.d)
    .map(
      ([key, value]) => `
  if (!_value.has("${key}"))
    return std::nullopt;
  auto _${key}_opt_ = from_json<${getTypeName(value, true)}>(_value["${key}"]);
  if (!_${key}_opt_.has_value())
    return std::nullopt;
  `,
    )
    .join('\n  ')}
  Shared::${name} _res{std::move(*_base), ${
    // std::move the fields of the base, plus the inherited fields
    Object.entries(item.d)
      .map(([key, value]) => `std::move(*_${key}_opt_)`)
      .join(', ')
  }};

  return _res;
}
#pragma endregion JSON serialization for object ${name}
`);
};
const usingType: EmitItem<Types> = async (writer, name, item) => {
  // This is a base type, so we don't need to do anything special
  await writer.write(`
using ${name} = ${getTypeName(item)};
`);
};

export const CppEmitter: Emitter = {
  header,
  footer,
  types: {
    objType,
    subType,
    arrType: usingType,
    setType: usingType,
    fastSetType: usingType,
    mapType: usingType,
    fastMapType: usingType,
    tupType: usingType,
    enumType,
    strType: usingType,
    numEnumType,
    strEnumType,
  },
};

export function GetCppGenerator(): FileGenerator {
  // Returns the CppEmitter instance
  return MakeGenerator(CppEmitter);
}
