#pragma once
// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from ./cpptests/test-input.ts by running 'crow-idl
// ...'. If you need to change this file, edit ./cpptests/test-input.ts and run
// the crow-idl command again. Or, if you need to change the generation process,
// put up a pull-request to https://github.com/kevinfrei/ts-cpp-tooling
// DO NOT EDIT THIS FILE DIRECTLY!!!

// Generated by @freik/ts-cpp-tooling v0.6.0

#include <charconv>
#include <cstddef>
#include <cstdint>
#include <iomanip>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <crow/json.h>

// TODO: Configure this header to be an external blob

/****
Conversion to JSON stuff
****/

// Helper stuff I need
// bool value for an enum-class to enable JSON specialization
template <typename T>
struct is_enum_class {
  static constexpr bool value =
      std::is_enum_v<T> && !std::is_convertible_v<T, int>;
};

template <typename T>
inline constexpr bool is_enum_class_v = is_enum_class<T>::value;

template <typename T>
constexpr auto underlying_cast(T e) noexcept {
  static_assert(std::is_enum_v<T>,
                "underlying_cast can only be used with enum types.");
  return static_cast<std::underlying_type_t<T>>(e);
}

/****
Conversion to JSON stuff
****/

// By default, simple stuff can be converted to json
// The enable_if_t is to prevent this version from being used by enum classes,
// which get extra validation to prevent stupidity from accidentally leaking.
template <typename T, typename Enabled = void>
struct impl_to_json {
  static inline crow::json::wvalue process(const T& value) {
    return crow::json::wvalue(value);
  }
};

template <typename T>
inline std::enable_if_t<!is_enum_class_v<T>, crow::json::wvalue> to_json(
    const T& value) {
  return impl_to_json<T>::process(value);
}

template <typename T>
inline std::enable_if_t<is_enum_class_v<T>, crow::json::wvalue> to_json(
    const T value) {
  return crow::json::wvalue(static_cast<std::underlying_type_t<T>>(value));
}

// A little extra work for string constants:

// Function to manually escape a string for JSON
inline std::string escape_json_string(std::string_view sv) {
  std::ostringstream o;
  for (char c : sv) {
    if (c == '"') {
      o << "\\\"";
    } else if (c == '\\') {
      o << "\\\\";
    } else if (c == '\b') {
      o << "\\b";
    } else if (c == '\f') {
      o << "\\f";
    } else if (c == '\n') {
      o << "\\n";
    } else if (c == '\r') {
      o << "\\r";
    } else if (c == '\t') {
      o << "\\t";
    } else if (static_cast<unsigned char>(c) < 0x20 ||
               static_cast<unsigned char>(c) > 0x7e) {
      // Escape other control characters and non-ASCII characters as \uXXXX
      o << "\\u" << std::hex << std::setw(4) << std::setfill('0')
        << static_cast<int>(static_cast<unsigned char>(c));
    } else {
      o << c;
    }
  }
  return o.str();
}

template <>
struct impl_to_json<std::string> {
  static inline crow::json::wvalue process(const std::string& value) {
    return crow::json::wvalue(escape_json_string(value));
  }
};
template <>
struct impl_to_json<char*> {
  static inline crow::json::wvalue process(const char* value) {
    return crow::json::wvalue(escape_json_string(value));
  }
};

template <>
struct impl_to_json<uint64_t> {
  static inline crow::json::wvalue process(const uint64_t& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.BigInt";
    v["@dataValue"] = std::to_string(value);
    return v;
  }
};

template <>
struct impl_to_json<int64_t> {
  static inline crow::json::wvalue process(const int64_t& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.BigInt";
    v["@dataValue"] = std::to_string(value);
    return v;
  }
};

template <>
struct impl_to_json<std::string_view> {
  static inline crow::json::wvalue process(std::string_view value) {
    return crow::json::wvalue(escape_json_string(value));
  }
};

// Vector<T> specialization
template <typename T>
struct impl_to_json<std::vector<T>> {
  static inline crow::json::wvalue process(const std::vector<T>& value) {
    crow::json::wvalue vec{std::vector<crow::json::wvalue>()};
    for (uint32_t i = 0; i < value.size(); i++) {
      vec[i] = to_json(value[i]);
    }
    return vec;
  }
};

// Handle char's specifically. Hurray dumb Javascript?
template <>
struct impl_to_json<char> {
  static inline crow::json::wvalue process(char value) {
    return crow::json::wvalue(std::string(1, value));
  }
};

template <typename... Args>
struct impl_to_json<std::tuple<Args...>> {
  using tup_type = std::tuple<Args...>;
  // Tuples in JSON are "just" arrays with the right size & types.
  // Doing that is...complicated.
  template <size_t Index, typename T>
  static inline void element_helper(const tup_type& tuple,
                                    crow::json::wvalue& container) {
    container[Index] = to_json(std::get<Index>(tuple));
  }
  // This is a compile time 'call the helper for each type' thing.
  template <size_t... Is>
  static inline void recurse_helper(const tup_type& tuple,
                                    crow::json::wvalue& json_list,
                                    std::index_sequence<Is...>) {
    ((element_helper<Is, std::tuple_element_t<Is, tup_type>>(tuple, json_list)),
     ...);
  }
  // make_index_sequence is the magic to do something different per tuple-item
  static inline crow::json::wvalue process(const std::tuple<Args...>& value) {
    crow::json::wvalue vec{std::vector<crow::json::wvalue>()};
    recurse_helper(value, vec, std::make_index_sequence<sizeof...(Args)>{});
    return vec;
  }
};

// I didn't need this for Windows, but I do for Linux/Mac because the map
// elem type is std::tuple on one, but a std::pair on the other
template <typename Iter>
inline crow::json::wvalue impl_vec_pair_to_json(const Iter& begin,
                                                const Iter& end) {
  std::vector<crow::json::wvalue> vec;
  for (auto it = begin; it != end; ++it) {
    crow::json::wvalue pair{std::vector<crow::json::wvalue>()};
    auto& [first, second] = *it;
    pair[0] = to_json(first);
    pair[1] = to_json(second);
    vec.push_back(pair);
  }
  return vec;
}

// My pickling framework sends JS Maps as this:
// {"@dataType":"freik.Map","@dataValue":[["a",1],["c",2],["b",3]]}
template <typename K, typename V>
struct impl_to_json<std::map<K, V>> {
  static inline crow::json::wvalue process(const std::map<K, V>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Map";
    v["@dataValue"] = impl_vec_pair_to_json(value.begin(), value.end());
    return v;
  }
};

template <typename K, typename V>
struct impl_to_json<std::unordered_map<K, V>> {
  static inline crow::json::wvalue process(
      const std::unordered_map<K, V>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Map";
    v["@dataValue"] = impl_vec_pair_to_json(value.begin(), value.end());
    return v;
  }
};

// My pickling framework sends JS Sets as this:
// {"@dataType":"freik.Set","@dataValue":["a", "c", "b"]}
template <typename T>
struct impl_to_json<std::unordered_set<T>> {
  static inline crow::json::wvalue process(const std::unordered_set<T>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Set";
    std::vector<T> flat;
    flat.reserve(value.size());
    flat.assign(value.begin(), value.end());
    v["@dataValue"] = to_json(flat);
    return v;
  }
};

template <typename T>
struct impl_to_json<std::set<T>> {
  static inline crow::json::wvalue process(const std::set<T>& value) {
    crow::json::wvalue v;
    v["@dataType"] = "freik.Set";
    std::vector<T> flat;
    flat.reserve(value.size());
    flat.assign(value.begin(), value.end());
    v["@dataValue"] = to_json(flat);
    return v;
  }
};

template <typename T>
struct impl_to_json<std::optional<T>> {
  static inline crow::json::wvalue process(const std::optional<T>& value) {
    if (value.has_value()) {
      return to_json(*value);
    } else {
      return crow::json::wvalue(nullptr);
    }
  }
};

/****
Conversion from JSON stuff
****/

// By default, we can't read a random value from a json value
// (i.e. everything must be specialized) and it's easier to
// do this with a partial specialization of a struct :/
template <typename T, typename Enabled = void>
struct impl_from_json {
  static inline std::optional<T> process(const crow::json::rvalue&) {
    return std::nullopt;
  }
};

// Anything that doesn't either fully specialize this function,
// or partially (or fully...) specialize the above struct gets std::nullopt.
template <typename T>
inline std::optional<T> from_json(const crow::json::rvalue& json) {
  return impl_from_json<T>::process(json);
}

// Chars are a little weird, cuz, Javascript
template <>
inline std::optional<char> from_json<char>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::String) {
    return std::nullopt;
  }
  std::string str = json.s();
  if (str.size() != 1) {
    return std::nullopt;
  }
  return static_cast<char>(str[0]);
}

template <>
inline std::optional<uint8_t> from_json<uint8_t>(
    const crow::json::rvalue& json) {
  if (json.nt() != crow::json::num_type::Unsigned_integer) {
    return std::nullopt;
  }
  return static_cast<uint8_t>(json.u());
}

template <>
inline std::optional<int8_t> from_json<int8_t>(const crow::json::rvalue& json) {
  if (json.nt() == crow::json::num_type::Floating_point) {
    return std::nullopt;
  }
  return static_cast<int8_t>(json.u());
}

template <>
inline std::optional<uint16_t> from_json<uint16_t>(
    const crow::json::rvalue& json) {
  if (json.nt() != crow::json::num_type::Unsigned_integer) {
    return std::nullopt;
  }
  return static_cast<uint16_t>(json.u());
}

template <>
inline std::optional<int16_t> from_json<int16_t>(
    const crow::json::rvalue& json) {
  if (json.nt() == crow::json::num_type::Floating_point) {
    return std::nullopt;
  }
  return static_cast<int16_t>(json.u());
}

template <>
inline std::optional<uint32_t> from_json<uint32_t>(
    const crow::json::rvalue& json) {
  if (json.nt() != crow::json::num_type::Unsigned_integer) {
    return std::nullopt;
  }
  return static_cast<uint32_t>(json.u());
}

template <>
inline std::optional<int32_t> from_json<int32_t>(
    const crow::json::rvalue& json) {
  if (json.nt() == crow::json::num_type::Floating_point) {
    return std::nullopt;
  }
  return static_cast<int32_t>(json.u());
}

template <>
inline std::optional<uint64_t> from_json<uint64_t>(
    const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Object || json.size() != 2) {
    return std::nullopt;
  }
  if (json["@dataType"].s() != "freik.BigInt") {
    return std::nullopt;
  }
  auto dataValue = json["@dataValue"];
  if (dataValue.t() != crow::json::type::String) {
    return std::nullopt;
  }
  std::string str = dataValue.s();
  return std::stoull(str);
}

template <>
inline std::optional<int64_t> from_json<int64_t>(
    const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Object || json.size() != 2) {
    return std::nullopt;
  }
  if (json["@dataType"].s() != "freik.BigInt") {
    return std::nullopt;
  }
  auto dataValue = json["@dataValue"];
  if (dataValue.t() != crow::json::type::String) {
    return std::nullopt;
  }
  std::string str = dataValue.s();
  return std::stoll(str);
}

template <>
inline std::optional<float> from_json<float>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Number) {
    return std::nullopt;
  }
  return static_cast<float>(json.d());
}

template <>
inline std::optional<double> from_json<double>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::Number) {
    return std::nullopt;
  }
  return static_cast<double>(json.d());
}

template <>
inline std::optional<bool> from_json<bool>(const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::True &&
      json.t() != crow::json::type::False) {
    return std::nullopt;
  }
  return json.t() == crow::json::type::True;
}

template <>
inline std::optional<std::string> from_json<std::string>(
    const crow::json::rvalue& json) {
  if (json.t() != crow::json::type::String) {
    return std::nullopt;
  }
  return std::string(json.s());
}

// std::vector specialization:
template <typename T>
struct impl_from_json<std::vector<T>> {
  using value_type = T;
  static inline std::optional<std::vector<value_type>> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::List) {
      return std::nullopt;
    }
    std::vector<value_type> vec;
    vec.reserve(json.size());
    for (size_t i = 0; i < json.size(); i++) {
      auto item = from_json<value_type>(json[i]);
      if (!item) {
        return std::nullopt;
      }
      vec.push_back(*item);
    }
    return vec;
  }
};

// std::tuple specialization:
// TODO: Explain this, as it is rather messsy.
template <typename... Args>
struct impl_from_json<std::tuple<Args...>> {
 private:
  using tup_type = std::tuple<Args...>;
  template <size_t Index, typename T>
  static inline std::optional<T> element_helper(
      tup_type& tuple, bool& failed, const crow::json::rvalue& container) {
    std::optional<T> res = from_json<T>(container[Index]);
    failed = failed || !res.has_value();
    if (res.has_value()) {
      std::get<Index>(tuple) = res.value();
    }
    return res;
  }

  template <size_t... Is>
  static inline std::optional<tup_type> recurse(
      const crow::json::rvalue& container, std::index_sequence<Is...>) {
    tup_type res;
    bool failed = false;
    ((element_helper<Is, std::tuple_element_t<Is, tup_type>>(
         res, failed, container)),
     ...);
    if (failed)
      return std::nullopt;
    return res;
  }

 public:
  static inline std::optional<tup_type> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::List) {
      return std::nullopt;
    }
    // Check exact tuple size
    if (json.size() != sizeof...(Args)) {
      return std::nullopt;
    }
    tup_type t;
    return recurse(json, std::make_index_sequence<sizeof...(Args)>{});
  }
};

// std::set/unordered_set specialization common code:
template <template <typename...> class SetType, typename Elem>
struct impl_set_helper_from_json {
  static inline std::optional<SetType<Elem>> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::Object || json.size() != 2) {
      return std::nullopt;
    }
    if (json["@dataType"].s() != "freik.Set") {
      return std::nullopt;
    }
    auto dataValue = json["@dataValue"];
    if (dataValue.t() != crow::json::type::List) {
      return std::nullopt;
    }
    SetType<Elem> m;
    for (const auto& item : dataValue) {
      auto value = from_json<Elem>(item);
      if (!value) {
        return std::nullopt;
      }
      m.insert(*value);
    }
    return m;
  }
};

// std::set specialization
template <typename Elem>
struct impl_from_json<std::set<Elem>> {
  static inline std::optional<std::set<Elem>> process(
      const crow::json::rvalue& json) {
    return impl_set_helper_from_json<std::set, Elem>::process(json);
  }
};

// std::unordered_set specialization
template <typename Elem>
struct impl_from_json<std::unordered_set<Elem>> {
  static inline std::optional<std::unordered_set<Elem>> process(
      const crow::json::rvalue& json) {
    return impl_set_helper_from_json<std::unordered_set, Elem>::process(json);
  }
};

// std::map/unordered specialization helper:
template <template <typename...> class MapType, typename K, typename V>
struct impl_map_helper_from_json {
  static inline std::optional<MapType<K, V>> process(
      const crow::json::rvalue& json) {
    if (json.t() != crow::json::type::Object || json.size() != 2) {
      return std::nullopt;
    }
    if (json["@dataType"].s() != "freik.Map") {
      return std::nullopt;
    }
    auto dataValue = json["@dataValue"];
    if (dataValue.t() != crow::json::type::List) {
      return std::nullopt;
    }
    MapType<K, V> m;
    for (const auto& item : dataValue) {
      if (item.t() != crow::json::type::List || item.size() != 2) {
        return std::nullopt;
      }
      auto key = from_json<K>(item[0]);
      auto value = from_json<V>(item[1]);
      if (!key || !value) {
        return std::nullopt;
      }
      m[*key] = *value;
    }
    return m;
  }
};

// std::map specialization
template <typename K, typename V>
struct impl_from_json<std::map<K, V>> {
  static inline std::optional<std::map<K, V>> process(
      const crow::json::rvalue& json) {
    return impl_map_helper_from_json<std::map, K, V>::process(json);
  }
};

// std::unordered_set specialization
template <typename K, typename V>
struct impl_from_json<std::unordered_map<K, V>> {
  static inline std::optional<std::unordered_map<K, V>> process(
      const crow::json::rvalue& json) {
    return impl_map_helper_from_json<std::unordered_map, K, V>::process(json);
  }
};

// Enum's, specifically for my gen'ed enum types, which include an
// 'is_valid' free function overload
template <typename T>
struct impl_from_json<T, std::enable_if_t<is_enum_class_v<T>>> {
  static inline std::optional<T> process(const crow::json::rvalue& json) {
    using IntType = std::underlying_type_t<T>;
    std::optional<IntType> underlyingValue = from_json<IntType>(json);
    if (!underlyingValue.has_value())
      return std::nullopt;
    T val = static_cast<T>(underlyingValue.value());
    // Check that the enumeration is actually defined
    if (is_valid(val))
      return val;
    return std::nullopt;
  }
};

/* Horsing around a little bit
template <typename T>
struct impl_from_json<std::optional<T>> {
  static inline std::optional<std::optional<T>> process(
      const crow::json::rvalue& json) {
    if (json.t() == crow::json::type::Null) {
      return std::nullopt;
    }
    auto val = from_json<T>(json);
    if (!val.has_value()) {
      return std::nullopt;
    }
    return val;
  }
};
*/

// TODO: End Configure this header to be an external blob

namespace Shared {

template <typename T>
constexpr std::optional<T> from_string(std::string_view str);

using MyI8 = std::int8_t;
using MyI16 = std::int16_t;
using MyI32 = std::int32_t;
using MyI64 = std::int64_t;
using MyU8 = std::uint8_t;
using MyU16 = std::uint16_t;
using MyU32 = std::uint32_t;
using MyU64 = std::uint64_t;
using MyFloat = float;
using MyDouble = double;
using MyString = std::string;
using MyBoolean = bool;
using MyChar = char;
using Int8Array = std::vector<std::int8_t>;
using Int16Set = std::set<std::int16_t>;
using CharFastSet = std::unordered_set<char>;
using Int32toStrMap = std::map<std::int32_t, std::string>;
using StrToU16FastMap = std::unordered_map<std::string, std::uint16_t>;

struct MyObj {
  std::string a;
  std::int32_t b;
  bool c;
  std::optional<char> d;
};

struct MySub : public MyObj {
  std::string x;
  std::int32_t y;
};
using MyTup = std::tuple<std::string, std::int32_t, bool>;

#pragma region numeric enum MyEnum
enum class MyEnum : std::uint8_t { a, b, c };

inline constexpr bool is_valid(MyEnum _value) {
  switch (_value) {
    case MyEnum::a:
    case MyEnum::b:
    case MyEnum::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(MyEnum _value) {
  switch (_value) {
    case MyEnum::a:
      return "a";
    case MyEnum::b:
      return "b";
    case MyEnum::c:
      return "c";
    default:
      return "<unknown>";
  }
}

// Could be itoa with a cast, but string_view's...
inline constexpr std::string_view to_string(MyEnum _value) {
  switch (_value) {
    case MyEnum::a:
      return "0";
    case MyEnum::b:
      return "1";
    case MyEnum::c:
      return "2";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<MyEnum> from_string<MyEnum>(
    std::string_view _str) {
  std::uint8_t _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  MyEnum _res = static_cast<MyEnum>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion numeric enum MyEnum

#pragma region numeric enum MyEnum2
enum class MyEnum2 { a, b, c };

inline constexpr bool is_valid(MyEnum2 _value) {
  switch (_value) {
    case MyEnum2::a:
    case MyEnum2::b:
    case MyEnum2::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(MyEnum2 _value) {
  switch (_value) {
    case MyEnum2::a:
      return "a";
    case MyEnum2::b:
      return "b";
    case MyEnum2::c:
      return "c";
    default:
      return "<unknown>";
  }
}

// Could be itoa with a cast, but string_view's...
inline constexpr std::string_view to_string(MyEnum2 _value) {
  switch (_value) {
    case MyEnum2::a:
      return "0";
    case MyEnum2::b:
      return "1";
    case MyEnum2::c:
      return "2";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<MyEnum2> from_string<MyEnum2>(
    std::string_view _str) {
  int _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  MyEnum2 _res = static_cast<MyEnum2>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion numeric enum MyEnum2

#pragma region linear enum MyNEnum
enum class MyNEnum : std::int32_t {
  a = 1,
  b = 2,
  c = 3,
};

inline constexpr bool is_valid(MyNEnum _value) {
  switch (_value) {
    case MyNEnum::a:
    case MyNEnum::b:
    case MyNEnum::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(MyNEnum _value) {
  switch (_value) {
    case MyNEnum::a:
      return "a";
    case MyNEnum::b:
      return "b";
    case MyNEnum::c:
      return "c";
    default:
      return "<unknown>";
  }
}

inline constexpr std::string_view to_string(MyNEnum _value) {
  switch (_value) {
    case MyNEnum::a:
      return "1";
    case MyNEnum::b:
      return "2";
    case MyNEnum::c:
      return "3";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<MyNEnum> from_string<MyNEnum>(
    std::string_view _str) {
  std::int32_t _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  MyNEnum _res = static_cast<MyNEnum>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion linear enum MyNEnum

#pragma region linear enum MyNEnum2
enum class MyNEnum2 {
  a = 1,
  b = 2,
  c = 3,
};

inline constexpr bool is_valid(MyNEnum2 _value) {
  switch (_value) {
    case MyNEnum2::a:
    case MyNEnum2::b:
    case MyNEnum2::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(MyNEnum2 _value) {
  switch (_value) {
    case MyNEnum2::a:
      return "a";
    case MyNEnum2::b:
      return "b";
    case MyNEnum2::c:
      return "c";
    default:
      return "<unknown>";
  }
}

inline constexpr std::string_view to_string(MyNEnum2 _value) {
  switch (_value) {
    case MyNEnum2::a:
      return "1";
    case MyNEnum2::b:
      return "2";
    case MyNEnum2::c:
      return "3";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<MyNEnum2> from_string<MyNEnum2>(
    std::string_view _str) {
  int _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  MyNEnum2 _res = static_cast<MyNEnum2>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion linear enum MyNEnum2

#pragma region string enum MySEnum

enum class MySEnum { a, b, c };

inline constexpr bool is_valid(MySEnum _value) {
  switch (_value) {
    case MySEnum::a:
    case MySEnum::b:
    case MySEnum::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(MySEnum _value) {
  switch (_value) {
    case MySEnum::a:
      return "apple";
    case MySEnum::b:
      return "banana";
    case MySEnum::c:
      return "cherry";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<MySEnum> from_string<MySEnum>(
    std::string_view str) {
  if (str == "apple")
    return MySEnum::a;
  if (str == "banana")
    return MySEnum::b;
  if (str == "cherry")
    return MySEnum::c;
  return std::nullopt;
}

#pragma endregion string enum MySEnum

struct Aggregate {
  MyEnum le;
  MyNEnum ne;
  MySEnum se;
};

struct Aggregate2 {
  MyTup tup;
  std::optional<MySub> opt;
};
using Aggregate3 = std::vector<Aggregate2>;

} // namespace Shared

#pragma region JSON serialization for object MyObj
template <>
struct impl_to_json<Shared::MyObj> {
  static inline crow::json::wvalue process(const Shared::MyObj& _value) {
    crow::json::wvalue _res;
    _res["a"] = to_json(_value.a);
    _res["b"] = to_json(_value.b);
    _res["c"] = to_json(_value.c);
    if (_value.d) {
      _res["d"] = to_json(*_value.d);
    }
    return _res;
  }
};

template <>
inline std::optional<Shared::MyObj> from_json<Shared::MyObj>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::MyObj _res;

  if (!_value.has("a"))
    return std::nullopt;
  auto _a_opt_ = from_json<std::string>(_value["a"]);
  if (!_a_opt_.has_value())
    return std::nullopt;
  _res.a = std::move(*_a_opt_);

  if (!_value.has("b"))
    return std::nullopt;
  auto _b_opt_ = from_json<std::int32_t>(_value["b"]);
  if (!_b_opt_.has_value())
    return std::nullopt;
  _res.b = std::move(*_b_opt_);

  if (!_value.has("c"))
    return std::nullopt;
  auto _c_opt_ = from_json<bool>(_value["c"]);
  if (!_c_opt_.has_value())
    return std::nullopt;
  _res.c = std::move(*_c_opt_);

  if (_value.has("d")) {
    auto _d_opt_ = from_json<char>(_value["d"]);
    if (!_d_opt_.has_value())
      return std::nullopt;
    _res.d = std::move(*_d_opt_);
  } else {
    _res.d = std::nullopt;
  }
  return _res;
}
#pragma endregion JSON serialization for object MyObj

#pragma region JSON serialization for object MySub
template <>
struct impl_to_json<Shared::MySub> {
  static inline crow::json::wvalue process(const Shared::MySub& _value) {
    crow::json::wvalue _res = impl_to_json<Shared::MyObj>::process(_value);
    _res["x"] = to_json(_value.x);
    _res["y"] = to_json(_value.y);
    return _res;
  }
};

template <>
inline std::optional<Shared::MySub> from_json<Shared::MySub>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  std::optional<Shared::MyObj> _base = from_json<Shared::MyObj>(_value);
  if (!_base.has_value())
    return std::nullopt;

  if (!_value.has("x"))
    return std::nullopt;
  auto _x_opt_ = from_json<std::string>(_value["x"]);
  if (!_x_opt_.has_value())
    return std::nullopt;

  if (!_value.has("y"))
    return std::nullopt;
  auto _y_opt_ = from_json<std::int32_t>(_value["y"]);
  if (!_y_opt_.has_value())
    return std::nullopt;
  Shared::MySub _res{
      std::move(*_base), std::move(*_x_opt_), std::move(*_y_opt_)};

  return _res;
}
#pragma endregion JSON serialization for object MySub
#pragma region JSON serialization for string enum MySEnum
template <>
inline crow::json::wvalue to_json<Shared::MySEnum>(Shared::MySEnum _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::MySEnum> {
  static inline std::optional<Shared::MySEnum> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::MySEnum>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum MySEnum

#pragma region JSON serialization for object Aggregate
template <>
struct impl_to_json<Shared::Aggregate> {
  static inline crow::json::wvalue process(const Shared::Aggregate& _value) {
    crow::json::wvalue _res;
    _res["le"] = to_json(_value.le);
    _res["ne"] = to_json(_value.ne);
    _res["se"] = to_json(_value.se);

    return _res;
  }
};

template <>
inline std::optional<Shared::Aggregate> from_json<Shared::Aggregate>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::Aggregate _res;

  if (!_value.has("le"))
    return std::nullopt;
  auto _le_opt_ = from_json<Shared::MyEnum>(_value["le"]);
  if (!_le_opt_.has_value())
    return std::nullopt;
  _res.le = std::move(*_le_opt_);

  if (!_value.has("ne"))
    return std::nullopt;
  auto _ne_opt_ = from_json<Shared::MyNEnum>(_value["ne"]);
  if (!_ne_opt_.has_value())
    return std::nullopt;
  _res.ne = std::move(*_ne_opt_);

  if (!_value.has("se"))
    return std::nullopt;
  auto _se_opt_ = from_json<Shared::MySEnum>(_value["se"]);
  if (!_se_opt_.has_value())
    return std::nullopt;
  _res.se = std::move(*_se_opt_);

  return _res;
}
#pragma endregion JSON serialization for object Aggregate

#pragma region JSON serialization for object Aggregate2
template <>
struct impl_to_json<Shared::Aggregate2> {
  static inline crow::json::wvalue process(const Shared::Aggregate2& _value) {
    crow::json::wvalue _res;
    _res["tup"] = to_json(_value.tup);
    if (_value.opt) {
      _res["opt"] = to_json(*_value.opt);
    }
    return _res;
  }
};

template <>
inline std::optional<Shared::Aggregate2> from_json<Shared::Aggregate2>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::Aggregate2 _res;

  if (!_value.has("tup"))
    return std::nullopt;
  auto _tup_opt_ = from_json<Shared::MyTup>(_value["tup"]);
  if (!_tup_opt_.has_value())
    return std::nullopt;
  _res.tup = std::move(*_tup_opt_);

  if (_value.has("opt")) {
    auto _opt_opt_ = from_json<Shared::MySub>(_value["opt"]);
    if (!_opt_opt_.has_value())
      return std::nullopt;
    _res.opt = std::move(*_opt_opt_);
  } else {
    _res.opt = std::nullopt;
  }
  return _res;
}
#pragma endregion JSON serialization for object Aggregate2
