#pragma once
// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from ../cpptests/test-input.ts by running 'crow-idl
// ...'. If you need to change this file, edit ../cpptests/test-input.ts and run
// the crow-idl command again. Or, if you need to change the generation process,
// put up a pull-request to https://github.com/kevinfrei/ts-cpp-tooling
// DO NOT EDIT THIS FILE DIRECTLY!!!

// Generated by @freik/ts-cpp-tooling v0.5.0

#include <charconv>
#include <cstdint>
#include <map>
#include <optional>
#include <set>
#include <string_view>
#include <tuple>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <crow/json.h>

// TODO: Inline this?
#include "json_pickling.hpp"

namespace Shared {

template <typename T>
constexpr std::optional<T> from_string(std::string_view str);

using MyI8 = std::int8_t;
using MyI16 = std::int16_t;
using MyI32 = std::int32_t;
using MyI64 = std::int64_t;
using MyU8 = std::uint8_t;
using MyU16 = std::uint16_t;
using MyU32 = std::uint32_t;
using MyU64 = std::uint64_t;
using MyFloat = float;
using MyDouble = double;
using MyString = std::string;
using MyBoolean = bool;
using MyChar = char;
using Int8Array = std::vector<std::int8_t>;
using Int16Set = std::set<std::int16_t>;
using CharFastSet = std::unordered_set<char>;
using Int32toStrMap = std::map<std::int32_t, std::string>;
using StrToU16FastMap = std::unordered_map<std::string, std::uint16_t>;

struct MyObj {
  std::string a;
  std::int32_t b;
  bool c;
  std::optional<char> d;
};

struct MySub : public MyObj {
  std::string x;
  std::int32_t y;
};
using MyTup = std::tuple<std::string, std::int32_t, bool>;

#pragma region numeric enum MyEnum
enum class MyEnum : std::uint8_t { a, b, c };

inline constexpr bool is_valid(MyEnum _value) {
  switch (_value) {
    case MyEnum::a:
    case MyEnum::b:
    case MyEnum::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(MyEnum _value) {
  switch (_value) {
    case MyEnum::a:
      return "a";
    case MyEnum::b:
      return "b";
    case MyEnum::c:
      return "c";
    default:
      return "<unknown>";
  }
}

// Could be itoa with a cast, but string_view's...
inline constexpr std::string_view to_string(MyEnum _value) {
  switch (_value) {
    case MyEnum::a:
      return "0";
    case MyEnum::b:
      return "1";
    case MyEnum::c:
      return "2";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<MyEnum> from_string<MyEnum>(
    std::string_view _str) {
  std::uint8_t _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  MyEnum _res = static_cast<MyEnum>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion numeric enum MyEnum

#pragma region numeric enum MyEnum2
enum class MyEnum2 { a, b, c };

inline constexpr bool is_valid(MyEnum2 _value) {
  switch (_value) {
    case MyEnum2::a:
    case MyEnum2::b:
    case MyEnum2::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(MyEnum2 _value) {
  switch (_value) {
    case MyEnum2::a:
      return "a";
    case MyEnum2::b:
      return "b";
    case MyEnum2::c:
      return "c";
    default:
      return "<unknown>";
  }
}

// Could be itoa with a cast, but string_view's...
inline constexpr std::string_view to_string(MyEnum2 _value) {
  switch (_value) {
    case MyEnum2::a:
      return "0";
    case MyEnum2::b:
      return "1";
    case MyEnum2::c:
      return "2";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<MyEnum2> from_string<MyEnum2>(
    std::string_view _str) {
  int _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  MyEnum2 _res = static_cast<MyEnum2>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion numeric enum MyEnum2

#pragma region linear enum MyNEnum
enum class MyNEnum : std::int32_t {
  a = 1,
  b = 2,
  c = 3,
};

inline constexpr bool is_valid(MyNEnum _value) {
  switch (_value) {
    case MyNEnum::a:
    case MyNEnum::b:
    case MyNEnum::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(MyNEnum _value) {
  switch (_value) {
    case MyNEnum::a:
      return "a";
    case MyNEnum::b:
      return "b";
    case MyNEnum::c:
      return "c";
    default:
      return "<unknown>";
  }
}

inline constexpr std::string_view to_string(MyNEnum _value) {
  switch (_value) {
    case MyNEnum::a:
      return "1";
    case MyNEnum::b:
      return "2";
    case MyNEnum::c:
      return "3";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<MyNEnum> from_string<MyNEnum>(
    std::string_view _str) {
  std::int32_t _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  MyNEnum _res = static_cast<MyNEnum>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion linear enum MyNEnum

#pragma region linear enum MyNEnum2
enum class MyNEnum2 {
  a = 1,
  b = 2,
  c = 3,
};

inline constexpr bool is_valid(MyNEnum2 _value) {
  switch (_value) {
    case MyNEnum2::a:
    case MyNEnum2::b:
    case MyNEnum2::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_name(MyNEnum2 _value) {
  switch (_value) {
    case MyNEnum2::a:
      return "a";
    case MyNEnum2::b:
      return "b";
    case MyNEnum2::c:
      return "c";
    default:
      return "<unknown>";
  }
}

inline constexpr std::string_view to_string(MyNEnum2 _value) {
  switch (_value) {
    case MyNEnum2::a:
      return "1";
    case MyNEnum2::b:
      return "2";
    case MyNEnum2::c:
      return "3";
    default:
      return "<unknown>";
  }
}

template <>
inline constexpr std::optional<MyNEnum2> from_string<MyNEnum2>(
    std::string_view _str) {
  int _val;
  auto [ptr, ec] =
      std::from_chars(_str.data(), _str.data() + _str.size(), _val);
  if (ec != std::errc{}) {
    return std::nullopt;
  }
  MyNEnum2 _res = static_cast<MyNEnum2>(_val);
  if (is_valid(_res))
    return _res;
  return std::nullopt;
}

#pragma endregion linear enum MyNEnum2

#pragma region string enum MySEnum

enum class MySEnum { a, b, c };

inline constexpr bool is_valid(MySEnum _value) {
  switch (_value) {
    case MySEnum::a:
    case MySEnum::b:
    case MySEnum::c:
      return true;
    default:
      return false;
  }
}

inline constexpr std::string_view to_string(MySEnum _value) {
  switch (_value) {
    case MySEnum::a:
      return "apple";
    case MySEnum::b:
      return "banana";
    case MySEnum::c:
      return "cherry";
    default:
      return "<unknown>";
  }
}

// This is *super* simplistic, and should be optimized, cuz this is bad.
// A deeply nested switch statement would be pretty fun to generate...
template <>
inline constexpr std::optional<MySEnum> from_string<MySEnum>(
    std::string_view str) {
  if (str == "apple")
    return MySEnum::a;
  if (str == "banana")
    return MySEnum::b;
  if (str == "cherry")
    return MySEnum::c;
  return std::nullopt;
}

#pragma endregion string enum MySEnum

struct Aggregate {
  MyEnum le;
  MyNEnum ne;
  MySEnum se;
};

struct Aggregate2 {
  MyTup tup;
  std::optional<MySub> opt;
};
using Aggregate3 = std::vector<Aggregate2>;

} // namespace Shared

#pragma region JSON serialization for object MyObj
template <>
struct impl_to_json<Shared::MyObj> {
  static inline crow::json::wvalue process(const Shared::MyObj& _value) {
    crow::json::wvalue _res;
    _res["a"] = to_json(_value.a);
    _res["b"] = to_json(_value.b);
    _res["c"] = to_json(_value.c);
    if (_value.d) {
      _res["d"] = to_json(*_value.d);
    }
    return _res;
  }
};

template <>
inline std::optional<Shared::MyObj> from_json<Shared::MyObj>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::MyObj _res;

  if (!_value.has("a"))
    return std::nullopt;
  auto _a_opt_ = from_json<std::string>(_value["a"]);
  if (!_a_opt_.has_value())
    return std::nullopt;
  _res.a = std::move(*_a_opt_);

  if (!_value.has("b"))
    return std::nullopt;
  auto _b_opt_ = from_json<std::int32_t>(_value["b"]);
  if (!_b_opt_.has_value())
    return std::nullopt;
  _res.b = std::move(*_b_opt_);

  if (!_value.has("c"))
    return std::nullopt;
  auto _c_opt_ = from_json<bool>(_value["c"]);
  if (!_c_opt_.has_value())
    return std::nullopt;
  _res.c = std::move(*_c_opt_);

  if (_value.has("d")) {
    auto _d_opt_ = from_json<char>(_value["d"]);
    if (!_d_opt_.has_value())
      return std::nullopt;
    _res.d = std::move(*_d_opt_);
  } else {
    _res.d = std::nullopt;
  }
  return _res;
}
#pragma endregion JSON serialization for object MyObj

#pragma region JSON serialization for object MySub
template <>
struct impl_to_json<Shared::MySub> {
  static inline crow::json::wvalue process(const Shared::MySub& _value) {
    crow::json::wvalue _res = impl_to_json<Shared::MyObj>::process(_value);
    _res["x"] = to_json(_value.x);
    _res["y"] = to_json(_value.y);
    return _res;
  }
};

template <>
inline std::optional<Shared::MySub> from_json<Shared::MySub>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  std::optional<Shared::MyObj> _base = from_json<Shared::MyObj>(_value);
  if (!_base.has_value())
    return std::nullopt;

  if (!_value.has("x"))
    return std::nullopt;
  auto _x_opt_ = from_json<std::string>(_value["x"]);
  if (!_x_opt_.has_value())
    return std::nullopt;

  if (!_value.has("y"))
    return std::nullopt;
  auto _y_opt_ = from_json<std::int32_t>(_value["y"]);
  if (!_y_opt_.has_value())
    return std::nullopt;
  Shared::MySub _res{
      std::move(*_base), std::move(*_x_opt_), std::move(*_y_opt_)};

  return _res;
}
#pragma endregion JSON serialization for object MySub
#pragma region JSON serialization for string enum MySEnum
template <>
inline crow::json::wvalue to_json<Shared::MySEnum>(Shared::MySEnum _value) {
  return to_json(to_string(_value));
}
template <>
struct impl_from_json<Shared::MySEnum> {
  static inline std::optional<Shared::MySEnum> process(
      const crow::json::rvalue& _value) {
    if (_value.t() != crow::json::type::String)
      return std::nullopt;
    auto _str = _value.s();
    return Shared::from_string<Shared::MySEnum>(
        std::string_view{_str.begin(), _str.size()});
  }
};
#pragma endregion JSON serialization for string enum MySEnum

#pragma region JSON serialization for object Aggregate
template <>
struct impl_to_json<Shared::Aggregate> {
  static inline crow::json::wvalue process(const Shared::Aggregate& _value) {
    crow::json::wvalue _res;
    _res["le"] = to_json(_value.le);
    _res["ne"] = to_json(_value.ne);
    _res["se"] = to_json(_value.se);

    return _res;
  }
};

template <>
inline std::optional<Shared::Aggregate> from_json<Shared::Aggregate>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::Aggregate _res;

  if (!_value.has("le"))
    return std::nullopt;
  auto _le_opt_ = from_json<Shared::MyEnum>(_value["le"]);
  if (!_le_opt_.has_value())
    return std::nullopt;
  _res.le = std::move(*_le_opt_);

  if (!_value.has("ne"))
    return std::nullopt;
  auto _ne_opt_ = from_json<Shared::MyNEnum>(_value["ne"]);
  if (!_ne_opt_.has_value())
    return std::nullopt;
  _res.ne = std::move(*_ne_opt_);

  if (!_value.has("se"))
    return std::nullopt;
  auto _se_opt_ = from_json<Shared::MySEnum>(_value["se"]);
  if (!_se_opt_.has_value())
    return std::nullopt;
  _res.se = std::move(*_se_opt_);

  return _res;
}
#pragma endregion JSON serialization for object Aggregate

#pragma region JSON serialization for object Aggregate2
template <>
struct impl_to_json<Shared::Aggregate2> {
  static inline crow::json::wvalue process(const Shared::Aggregate2& _value) {
    crow::json::wvalue _res;
    _res["tup"] = to_json(_value.tup);
    if (_value.opt) {
      _res["opt"] = to_json(*_value.opt);
    }
    return _res;
  }
};

template <>
inline std::optional<Shared::Aggregate2> from_json<Shared::Aggregate2>(
    const crow::json::rvalue& _value) {
  if (_value.t() != crow::json::type::Object)
    return std::nullopt;
  Shared::Aggregate2 _res;

  if (!_value.has("tup"))
    return std::nullopt;
  auto _tup_opt_ = from_json<Shared::MyTup>(_value["tup"]);
  if (!_tup_opt_.has_value())
    return std::nullopt;
  _res.tup = std::move(*_tup_opt_);

  if (_value.has("opt")) {
    auto _opt_opt_ = from_json<Shared::MySub>(_value["opt"]);
    if (!_opt_opt_.has_value())
      return std::nullopt;
    _res.opt = std::move(*_opt_opt_);
  } else {
    _res.opt = std::nullopt;
  }
  return _res;
}
#pragma endregion JSON serialization for object Aggregate2
