// DO NOT EDIT THIS FILE DIRECTLY!!!
// This file is generated from ../cpptests/test-input.ts.
// If you need to change this file, edit ../cpptests/test-input.ts and
// regenerate it.
// DO NOT EDIT THIS FILE DIRECTLY!!!

// Generated by @freik/ts-cpp-tooling v0.4.2

import * as TC from '@freik/typechk';

// TODO: Only emit the type checks that are needed

const chkIdlU8 = (v: unknown): v is number =>
  TC.isNumber(v) && v >= 0 && v <= 255 && Number.isInteger(v);

const chkIdlI8 = (v: unknown): v is number =>
  TC.isNumber(v) && v >= -128 && v <= 127 && Number.isInteger(v);

const chkIdlU16 = (v: unknown): v is number =>
  TC.isNumber(v) && v >= 0 && v <= 65535 && Number.isInteger(v);

const chkIdlI16 = (v: unknown): v is number =>
  TC.isNumber(v) && v >= -32768 && v <= 32767 && Number.isInteger(v);

const chkIdlU32 = (v: unknown): v is number =>
  TC.isNumber(v) && v >= 0 && v <= 4294967295 && Number.isInteger(v);

const chkIdlI32 = (v: unknown): v is number =>
  TC.isNumber(v) && v >= -2147483648 && v <= 2147483647 && Number.isInteger(v);

function chkIdlU64(v: unknown): v is number {
  if (TC.isNumber(v)) {
    return Number.isInteger(v) && chkIdlU64(BigInt(v));
  }
  return TC.isBigInt(v) && BigInt.asUintN(64, v) === v;
}

function chkIdlI64(v: unknown): v is number {
  if (TC.isNumber(v)) {
    return Number.isInteger(v) && chkIdlI64(BigInt(v));
  }
  return TC.isBigInt(v) && BigInt.asIntN(64, v) === v;
}

function chkIdlFloat(v: unknown): v is number {
  return (
    TC.isNumber(v) &&
    !Number.isNaN(v) &&
    Number.isFinite(Math.fround(v)) &&
    (v === 0 || Math.fround(v) !== 0)
  );
}

function chkIdlDouble(v: unknown): v is number {
  return TC.isNumber(v) && !Number.isNaN(v) && Number.isFinite(v);
}

function chkIdlChar(v: unknown): v is string {
  return TC.isString(v) && v.length === 1;
}

function chkOptional<T>(chk: TC.typecheck<T>): TC.typecheck<T | undefined> {
  return (v: unknown): v is T | undefined => v === undefined || chk(v);
}

export type MyI8 = number;
export const chkMyI8 = chkIdlI8;

export type MyI16 = number;
export const chkMyI16 = chkIdlI16;

export type MyI32 = number;
export const chkMyI32 = chkIdlI32;

export type MyI64 = bigint;
export const chkMyI64 = chkIdlI64;

export type MyU8 = number;
export const chkMyU8 = chkIdlU8;

export type MyU16 = number;
export const chkMyU16 = chkIdlU16;

export type MyU32 = number;
export const chkMyU32 = chkIdlU32;

export type MyU64 = bigint;
export const chkMyU64 = chkIdlU64;

export type MyFloat = number;
export const chkMyFloat = chkIdlFloat;

export type MyDouble = number;
export const chkMyDouble = chkIdlDouble;

export type MyString = string;
export const chkMyString = TC.isString;

export type MyBoolean = boolean;
export const chkMyBoolean = TC.isBoolean;

export type MyChar = string;
export const chkMyChar = chkIdlChar;

export type Int8Array = number[];
export const chkInt8Array = TC.chkArrayOf(chkIdlI8);

export type Int16Set = Set<number>;
export const chkInt16Set = TC.chkSetOf(chkIdlI16);

export type CharFastSet = Set<string>;
export const chkCharFastSet = TC.chkSetOf(chkIdlChar);

export type Int32toStrMap = Map<number, string>;
export const chkInt32toStrMap = TC.chkMapOf(chkIdlI32, TC.isString);

export type StrToU16FastMap = Map<string, number>;
export const chkStrToU16FastMap = TC.chkMapOf(TC.isString, chkIdlU16);

export type MyObj = {
  a: string;
  b: number;
  c: boolean;
  d?: string;
};
export const chkMyObj: TC.typecheck<MyObj> = TC.chkObjectOfType(
  {
    a: TC.isString,
    b: chkIdlI32,
    c: TC.isBoolean,
  },
  { d: chkOptional(chkIdlChar) },
);

export type MySub = MyObj & {
  x: string;
  y: number;
};
export const chkMySub: TC.typecheck<MySub> = TC.chkAllOf(
  chkMyObj,
  TC.chkFieldOf('x', TC.isString),
  TC.chkFieldOf('y', chkIdlI32),
);

export type MyTup = [string, number, boolean];
export const chkMyTup = TC.chkTupleOf(TC.isString, chkIdlI32, TC.isBoolean);

export const MyEnum = Object.freeze({
  a: 0,
  b: 1,
  c: 2,
});
export type MyEnum = (typeof MyEnum)[keyof typeof MyEnum];
export function chkMyEnum(val: unknown): val is MyEnum {
  return TC.isNumber(val) && Object.values(MyEnum).includes(val as MyEnum);
}

export const MyEnum2 = Object.freeze({
  a: 0,
  b: 1,
  c: 2,
});
export type MyEnum2 = (typeof MyEnum2)[keyof typeof MyEnum2];
export function chkMyEnum2(val: unknown): val is MyEnum2 {
  return TC.isNumber(val) && Object.values(MyEnum2).includes(val as MyEnum2);
}

export const MyNEnum = Object.freeze({
  a: 1,
  b: 2,
  c: 3,
});
export type MyNEnum = (typeof MyNEnum)[keyof typeof MyNEnum];
export function chkMyNEnum(val: unknown): val is MyNEnum {
  return TC.isNumber(val) && Object.values(MyNEnum).includes(val as MyNEnum);
}

export const MyNEnum2 = Object.freeze({
  a: 1,
  b: 2,
  c: 3,
});
export type MyNEnum2 = (typeof MyNEnum2)[keyof typeof MyNEnum2];
export function chkMyNEnum2(val: unknown): val is MyNEnum2 {
  return TC.isNumber(val) && Object.values(MyNEnum2).includes(val as MyNEnum2);
}

export const MySEnum = Object.freeze({
  a: 'apple',
  b: 'banana',
  c: 'cherry',
});
export type MySEnum = (typeof MySEnum)[keyof typeof MySEnum];
export function chkMySEnum(val: unknown): val is MySEnum {
  return TC.isString(val) && Object.values(MySEnum).includes(val as MySEnum);
}

export type Aggregate = {
  le: MyEnum;
  ne: MyNEnum;
  se: MySEnum;
};
export const chkAggregate: TC.typecheck<Aggregate> = TC.chkObjectOfType(
  {
    le: chkMyEnum,
    ne: chkMyNEnum,
    se: chkMySEnum,
  },
  {},
);

export type Aggregate2 = {
  tup: MyTup;
  opt?: MySub;
};
export const chkAggregate2: TC.typecheck<Aggregate2> = TC.chkObjectOfType(
  {
    tup: chkMyTup,
  },
  { opt: chkOptional(chkMySub) },
);

export type Aggregate3 = Aggregate2[];
export const chkAggregate3 = TC.chkArrayOf(chkAggregate2);

// End of generated code
