import {
  arr,
  bool,
  chr,
  dbl,
  enum_lst,
  enum_num,
  enum_str,
  flt,
  fmap,
  fset,
  i16,
  i32,
  i64,
  i8,
  map,
  obj,
  opt,
  ref,
  set,
  str,
  sub,
  tup,
  u16,
  u32,
  u64,
  u8,
} from '../src/crow-idl/IDL';
import { Types } from '../src/crow-idl/types';

export const TypesToGenerate: Record<string, Types> = {
  MyI8: i8(),
  MyI16: i16(),
  MyI32: i32(),
  MyI64: i64(),
  MyU8: u8(),
  MyU16: u16(),
  MyU32: u32(),
  MyU64: u64(),
  MyFloat: flt(),
  MyDouble: dbl(),
  MyString: str(),
  MyBoolean: bool(),
  MyChar: chr(),
  Int8Array: arr(i8()),
  Int16Set: set(i16()),
  CharFastSet: fset(chr()),
  Int32toStrMap: map(i32(), str()),
  StrToU16FastMap: fmap(str(), u16()),
  MyObj: obj({ a: str(), b: i32(), c: bool(), d: opt(chr()) }),
  MySub: sub('MyObj', { x: str(), y: i32() }),
  MyTup: tup(str(), i32(), bool()),
  MyOpt: opt(ref('MySub')),
  MyEnum: enum_lst(u8(), ['a', 'b', 'c']),
  MyNEnum: enum_num(i32(), { a: 1, b: 2, c: 3 }),
  MySEnum: enum_str({ a: 'apple', b: 'banana', c: 'cherry' }),
  Aggregate: obj({ le: ref('MyEnum'), ne: ref('MyNEnum'), se: ref('MySEnum') }),
  // Can you have a ref to an opt?
  Aggregate2: obj({ tup: ref('MyTup'), opt: ref('MyOpt') }),
  Aggreagte3: arr(ref('Aggregate2')),
};
